<?php

declare(strict_types=1);

function base_path(string $path = ''): string
{
    $scriptName = $_SERVER['SCRIPT_NAME'] ?? '/index.php';
    $baseDir = str_replace('\\', '/', dirname($scriptName));

    if ($baseDir === '.' || $baseDir === '/') {
        $baseDir = '';
    }

    $path = '/' . ltrim($path, '/');

    return $baseDir . $path;
}

function asset_url(string $path): string
{
    return base_path($path);
}

$form = [
    'project_name' => 'Mobile-first starter',
    'launch_window' => 'This week',
    'team_size' => 'Small team',
    'priority' => 'MVP first',
    'notes' => 'Tailwind CLI, PHP layout, and plain JavaScript.',
];

$submitted = false;

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    $submitted = true;
    $form = [
        'project_name' => trim((string) ($_POST['project_name'] ?? $form['project_name'])),
        'launch_window' => trim((string) ($_POST['launch_window'] ?? $form['launch_window'])),
        'team_size' => trim((string) ($_POST['team_size'] ?? $form['team_size'])),
        'priority' => trim((string) ($_POST['priority'] ?? $form['priority'])),
        'notes' => trim((string) ($_POST['notes'] ?? $form['notes'])),
    ];
}

$page = [
    'site_name' => 'Skeleton Build',
    'title' => 'Skeleton PHP Tailwind Starter',
    'description' => 'A mobile-first PHP starter with Tailwind CLI, CSS variables, and lightweight JavaScript.',
    'submitted' => $submitted,
    'form' => $form,
    'stats' => [
        ['label' => 'Stack', 'value' => 'PHP + Tailwind CLI'],
        ['label' => 'Style', 'value' => 'Mobile first'],
        ['label' => 'Palette', 'value' => 'CSS custom properties'],
    ],
    'features' => [
        [
            'title' => 'Structured layout',
            'description' => 'A shared PHP layout keeps the page shell, metadata, and asset links in one place.',
        ],
        [
            'title' => 'Theme variables',
            'description' => 'The theme colors live in one CSS file so the palette can be updated without touching markup.',
        ],
        [
            'title' => 'Local Tailwind build',
            'description' => 'Tailwind is compiled from a local input file with the CLI, no CDN required.',
        ],
    ],
    'file_map' => [
        'index.php' => 'Bootstraps the page, handles the demo form, and passes data into the layout.',
        'templates/layout.php' => 'Renders the HTML shell and the landing page sections.',
        'assets/css/input.css' => 'Tailwind source file and the theme variables.',
        'assets/css/styles.css' => 'Compiled stylesheet generated by the Tailwind CLI.',
        'assets/js/app.js' => 'Mobile navigation toggle and live preview updates.',
        'agents.md' => 'Plain-English map of what each file is responsible for.',
    ],
];

require __DIR__ . '/templates/layout.php';
